version: '3'

services:
  ap:
    # build: .
    image: jvm-student
    environment:
      JAVA_OPTS: "-XX:+UseG1GC -XX:StartFlightRecording=duration=240s,filename=/app/logs/JvmRecord.jfr,settings=profile -verbose:gc -Xlog:gc*:file=/app/logs/gc.log -XX:+PrintGCDetails"
      # JAVA_OPTS: "-XX:+UseSerialGC -XX:StartFlightRecording=delay=1s,duration=60s,filename=/var/log/JvmRecord.jfr,settings=profile"
      # JAVA_OPTS: "-XX:+UseSerialGC -XX:StartFlightRecording=delay=1s,duration=10s,filename=/var/log/myRecording.jfr,settings=profile,name=SampleRecording"
      # JAVA_OPTS: "-XX:+UseConcMarkSweepGC -Xmx:512m"
      # - JAVA_OPTS=-XX:+UseConcMarkSweepGC
    volumes:
      # - ./JvmRecord.jfr:/var/log/JvmRecord.jfr
      # - ./logs/JvmRecord.jfr:/app/logs/JvmRecord.jfr
      - ./logs/:/app/logs/
    deploy:
      resources:
        limits:
          cpus: '0'
          memory: 1g
